image: golang:1.17.2-stretch

gwat-build:
  stage: build
  tags:
    - docker
  #  rules:
  #    - if: '$CI_COMMIT_TAG == null'
  #      when: manual
  script:
    - cp -r params/version.go /tmp/version.go
    - sed -i "s/\\\u2692/${CI_COMMIT_SHORT_SHA}/g" params/version.go
    - cat params/version.go
    - go run build/ci.go install ./cmd/geth ./cmd/bootnode
    - mkdir -p ./dist
    - cp ./build/bin/bootnode ./dist/gwat-bootnode
    - cp ./build/bin/geth ./dist/gwat
    - cp -r /tmp/version.go params/version.go
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - dist/gwat-bootnode
      - dist/gwat
