image: golang:1.17.2
before_script:
  - apt-get update -y
  - apt-get install cmake git libssl-dev libgmp-dev libtinfo5 libprotoc-dev -y
  - echo "$GITCONFIG" > ~/.gitconfig
build:
  stage: build
  tags:
    - docker
  #  rules:
  #    - if: '$CI_COMMIT_TAG == null'
  #      when: manual
  script:
    - go run build/ci.go install ./cmd/geth ./cmd/bootnode
    - ls build/bin


cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in